---
product-name: pivotal-container-service
network-properties:
  network:
    name: pks
  service_network:
    name: services
  other_availability_zones:
    - name: ((availability_zones.0))
    - name: ((availability_zones.1))
    - name: ((availability_zones.2))
  singleton_availability_zone:
    name: ((availability_zones.0))
product-properties:
  .pivotal-container-service.pks_tls:
    value:
      cert_pem: |
        ((ssl_certificate))
      private_key_pem: |
        ((ssl_private_key))
  .properties.pks_api_hostname:
    value: api.((pks_api_dns_domain))
  .properties.plan1_selector.active.master_az_placement:
    value:
      - ((availability_zones.0))
  .properties.plan1_selector.active.worker_az_placement:
    value:
      - ((availability_zones.0))
      - ((availability_zones.1))
      - ((availability_zones.2))
  .properties.plan2_selector:
    value: "Plan Inactive"
  .properties.plan3_selector:
    value: "Plan Inactive"
  .properties.cloud_provider:
    value: GCP
  .properties.cloud_provider.gcp.project_id:
    value: ((project))
  .properties.cloud_provider.gcp.network:
    value: ((network_name))
  .properties.cloud_provider.gcp.master_service_account:
    value: ((pks_master_node_service_account_id))
  .properties.cloud_provider.gcp.worker_service_account:
    value: ((pks_worker_node_service_account_id))
  .properties.oidc_selector:
    value: disabled
  .properties.telemetry_selector:
    value: disabled
  .properties.telemetry_installation_purpose_selector:
    value: not_provided
resource-config:
  pivotal-container-service:
    elb_names:
      - tcp:((pks_api_target_pool_name))
errand-config:
  smoke-tests:
    post-deploy-state: true
