az-configuration:
- name: az1
  iaas_configuration_name: default
  clusters:
  - cluster: ((vcenter_cluster))
    drs_rule: MUST
    host_group: null
    resource_pool: RP-2-MGMT-TKGi
- name: az2
  iaas_configuration_name: default
  clusters:
  - cluster: ((vcenter_cluster))
    drs_rule: MUST
    host_group: null
    resource_pool: RP-2-MGMT-TKGi
iaas-configurations:
- additional_cloud_properties: {}
  bosh_disk_path: ((bosh_disk_path)) 
  bosh_template_folder: ((bosh_template_folder))
  bosh_vm_folder: ((bosh_vm_folder))
  datacenter: ((datacenter))
  disk_type: thin
  ephemeral_datastore_clusters_string: ""
  ephemeral_datastores_string: vsanDatastore
  name: dafault
  nsx_address: ((nsx_url))
  nsx_ca_certificate: ((nsx_ca_cert.public_key))
  nsx_mode: nsx-t
  nsx_networking_enabled: true
  nsx_password: ((iaas-configurations_0_nsx_password))
  nsx_t_auth_type: local_user
  nsx_t_use_policy_api: false
  nsx_username: admin
  persistent_datastore_clusters_string: ""
  persistent_datastores_string: ((persistent_datastores_string))
  ssl_verification_enabled: ((ssl_verification_enabled))
  vcenter_host: ((vcenter_url))
  vcenter_password: ((vcenter_password))
  vcenter_username: ((vcenter_username))
network-assignment:
  network:
    name: infra
  other_availability_zones: []
  singleton_availability_zone:
    name: az1
networks-configuration:
  icmp_checks_enabled: true
  networks:
  - name: ((vsphere_infra_network))
    subnets:
    - iaas_identifier: LS-PKS-Infra
      cidr: 192.168.1.0/24
      dns: 10.220.136.2,10.220.136.3
      gateway: 192.168.1.1
      reserved_ip_ranges: 192.168.1.1-192.168.1.12
      availability_zone_names:
      - az1
      - az2
  - name: ((vsphere_services_network))
    subnets:
    - iaas_identifier: LS-PKS-Deployment
      cidr: 192.168.2.0/24
      dns: 10.220.136.2,10.220.136.3
      gateway: 192.168.2.1
      reserved_ip_ranges: 192.168.2.1-192.168.2.8
      availability_zone_names:
      - az1
      - az2
properties-configuration:
  director_configuration:
    additional_ssh_users: []
    blobstore_type: local
    bosh_director_recreate_on_next_deploy: false
    bosh_recreate_on_next_deploy: false
    bosh_recreate_persistent_disks_on_next_deploy: false
    ca_certificate_duration: 1460
    database_type: internal
    director_metrics_server_enabled: true
    director_worker_count: 5
    duration_overrides_enabled: false
    encryption:
      keys: []
      providers: []
    hm_emailer_options:
      enabled: false
    hm_pager_duty_options:
      enabled: false
    identification_tags: {}
    job_configuration_on_tmpfs: false
    keep_unreachable_vms: false
    leaf_certificate_duration: 730
    local_blobstore_options:
      enable_signed_urls: true
    metrics_server_enabled: true
    ntp_servers_string: time1.oc.vmware.com,time2.oc.vmware.com,time3.oc.vmware.com,time4.oc.vmware.com
    post_deploy_enabled: false
    resurrector_enabled: true
    retry_bosh_deploys: false
    skip_director_drain: false
    system_metrics_runtime_enabled: true
  dns_configuration:
    excluded_recursors: []
    handlers: []
  security_configuration:
    clear_default_trusted_certificates_store: false
    generate_vm_passwords: true
    opsmanager_root_ca_trusted_certs: true
  syslog_configuration:
    enabled: false
resource-configuration:
  compilation:
    additional_networks: []
    additional_vm_extensions: []
    instance_type:
      id: large.disk
    instances: automatic
    nsx:
      lbs: []
      security_groups: []
    nsxt:
      lb:
        server_pools: []
      ns_groups: []
    swap_as_percent_of_memory_size: automatic
  director:
    additional_networks: []
    additional_vm_extensions: []
    instance_type:
      id: automatic
    instances: automatic
    nsx:
      lbs: []
      security_groups: []
    nsxt:
      lb:
        server_pools: []
      ns_groups: []
    persistent_disk:
      size_mb: "153600"
    swap_as_percent_of_memory_size: automatic
vmextensions-configuration: []
vmtypes-configuration: {}

