---
pivnet-product-slug: ops-manager
pivnet-file-glob: "ops-manager*.ova"
product-version: ((opsman-version))

s3-access-key-id: 1UbaH7dsjgxtKFLC
s3-secret-access-key: zT9pb8mCZzmiVYVKBV1j2icPp11cBw97
s3-bucket: s3pivnetproductbucket
s3-endpoint: http://10.220.54.169:9000
s3-disable-ssl: true
