---
opsman-configuration:
  vsphere:
    vcenter:
    #  ca_cert: cert                 # REQUIRED if insecure = 0 (secure)
      datacenter: ((datacenter))
      datastore: ((persistent_datastores_string))
      folder: /((datacenter))/vm/ # RECOMMENDED, but not required
      url: ((vcenter_url))
      username: ((vcenter_username))
      password: ((vcenter_password))
      resource_pool: /((datacenter))/host/((vcenter_cluster))/Resources/RP-2-MGMT-TKGi
      # resource_pool can use a cluster - /example-dc/host/example-cluster

      # Optional
      # host: host      # DEPRECATED - Platform Automation cannot guarantee
                        # the location of the VM, given the nature of vSphere
      insecure: 1     # default - 0 (secure) | 1 (insecure)

    disk_type: thin     # thin|thick
    dns: 10.220.136.2,10.220.136.3
    gateway: 192.168.1.1
    hostname: ((opsman_url))
    netmask: 255.255.255.0
    network: LS-PKS-Infra
    ntp: time1.oc.vmware.com,time2.oc.vmware.com,time3.oc.vmware.com,time4.oc.vmware.com
    private_ip: 192.168.1.3
    ssh_public_key: ((vsphere_ssh_key))
    vm_name: opsmanager2
